Задачи
Выделите из колонки attributes значение атрибута Parent. Т.е. если там записано Parent=x, то нам нужен x
Выясните, какое из этих значений является самым частым
Постройте распределение встречаемости значений в столбце type

In [1]:
import pandas as pd
import numpy as np
%matplotlib inline
import matplotlib.pyplot as plt
import seaborn as sns

import plotly.express as px

In [2]:
path_to_data = '/mnt/HC_Volume_18315164/home-jupyter/jupyter-i-kazantseva-40/shared/homeworks/python_ds_miniprojects/6_gff/gff.tsv'

In [8]:
gff = pd.read_csv(path_to_data, sep="\t")

In [9]:
gff

,seq_id,source,type,start,end,score,strand,phase,attributes
0,chr17,RefSeq,exon,6811330,6811453,.,+,.,Parent=XM_001475631.1
1,chr17,RefSeq,CDS,6808204,6808245,.,+,0,Name=CDS:NC_000083.5:LOC100040603;Parent=XM_00...
2,chr17,RefSeq,CDS,6811792,6811869,.,+,2,Name=CDS:NC_000083.5:LOC100040603;Parent=XM_00...
3,chr17,RefSeq,exon,6806513,6806553,.,+,.,Parent=XM_001475631.1
4,chr17,RefSeq,five_prime_UTR,6806513,6806526,.,+,.,Parent=XM_001475631.1
...,...,...,...,...,...,...,...,...,...
507,chr17,RefSeq,exon,6812219,6818159,.,+,.,Parent=XM_001475631.1
508,chr17,RefSeq,protein,6806527,6812289,.,+,.,ID=;Parent=XM_001475631.1
509,chr17,RefSeq,CDS,6806527,6806553,.,+,0,Name=CDS:NC_000083.5:LOC100040603;Parent=XM_00...
510,chr17,RefSeq,exon,6811792,6811869,.,+,.,Parent=XM_001475631.1
511,chr17,RefSeq,exon,6806513,6806553,.,+,.,Parent=XM_001475631.1

In [11]:
gff.attributes = gff.attributes.str.split(';')

In [12]:
gff.head()

,seq_id,source,type,start,end,score,strand,phase,attributes
0,chr17,RefSeq,exon,6811330,6811453,.,+,.,[Parent=XM_001475631.1]
1,chr17,RefSeq,CDS,6808204,6808245,.,+,0,"[Name=CDS:NC_000083.5:LOC100040603, Parent=XM_..."
2,chr17,RefSeq,CDS,6811792,6811869,.,+,2,"[Name=CDS:NC_000083.5:LOC100040603, Parent=XM_..."
3,chr17,RefSeq,exon,6806513,6806553,.,+,.,[Parent=XM_001475631.1]
4,chr17,RefSeq,five_prime_UTR,6806513,6806526,.,+,.,[Parent=XM_001475631.1]

In [19]:
def parent_search(stroka):
    for i in stroka:
        if 'Parent' in i:
            return i

In [21]:
gff['parent'] = gff.attributes.apply(parent_search)

In [22]:
gff.head()

,seq_id,source,type,start,end,score,strand,phase,attributes,parent
0,chr17,RefSeq,exon,6811330,6811453,.,+,.,[Parent=XM_001475631.1],Parent=XM_001475631.1
1,chr17,RefSeq,CDS,6808204,6808245,.,+,0,"[Name=CDS:NC_000083.5:LOC100040603, Parent=XM_...","Parent=XM_001475631.1,"
2,chr17,RefSeq,CDS,6811792,6811869,.,+,2,"[Name=CDS:NC_000083.5:LOC100040603, Parent=XM_...","Parent=XM_001475631.1,"
3,chr17,RefSeq,exon,6806513,6806553,.,+,.,[Parent=XM_001475631.1],Parent=XM_001475631.1
4,chr17,RefSeq,five_prime_UTR,6806513,6806526,.,+,.,[Parent=XM_001475631.1],Parent=XM_001475631.1

In [23]:
gff.parent = gff.parent.str.split('=')

In [24]:
gff.head()

,seq_id,source,type,start,end,score,strand,phase,attributes,parent
0,chr17,RefSeq,exon,6811330,6811453,.,+,.,[Parent=XM_001475631.1],"[Parent, XM_001475631.1]"
1,chr17,RefSeq,CDS,6808204,6808245,.,+,0,"[Name=CDS:NC_000083.5:LOC100040603, Parent=XM_...","[Parent, XM_001475631.1,]"
2,chr17,RefSeq,CDS,6811792,6811869,.,+,2,"[Name=CDS:NC_000083.5:LOC100040603, Parent=XM_...","[Parent, XM_001475631.1,]"
3,chr17,RefSeq,exon,6806513,6806553,.,+,.,[Parent=XM_001475631.1],"[Parent, XM_001475631.1]"
4,chr17,RefSeq,five_prime_UTR,6806513,6806526,.,+,.,[Parent=XM_001475631.1],"[Parent, XM_001475631.1]"

In [25]:
def XM_search(stroka):
    for i in stroka:
        if 'XM' in i:
            return i

In [26]:
gff['XM'] = gff.parent.apply(XM_search)

In [27]:
gff.head()

,seq_id,source,type,start,end,score,strand,phase,attributes,parent,XM
0,chr17,RefSeq,exon,6811330,6811453,.,+,.,[Parent=XM_001475631.1],"[Parent, XM_001475631.1]",XM_001475631.1
1,chr17,RefSeq,CDS,6808204,6808245,.,+,0,"[Name=CDS:NC_000083.5:LOC100040603, Parent=XM_...","[Parent, XM_001475631.1,]","XM_001475631.1,"
2,chr17,RefSeq,CDS,6811792,6811869,.,+,2,"[Name=CDS:NC_000083.5:LOC100040603, Parent=XM_...","[Parent, XM_001475631.1,]","XM_001475631.1,"
3,chr17,RefSeq,exon,6806513,6806553,.,+,.,[Parent=XM_001475631.1],"[Parent, XM_001475631.1]",XM_001475631.1
4,chr17,RefSeq,five_prime_UTR,6806513,6806526,.,+,.,[Parent=XM_001475631.1],"[Parent, XM_001475631.1]",XM_001475631.1

In [28]:
gff['XM'] = gff['XM'].str.strip(',')

In [31]:
gff

,seq_id,source,type,start,end,score,strand,phase,attributes,parent,XM
0,chr17,RefSeq,exon,6811330,6811453,.,+,.,[Parent=XM_001475631.1],"[Parent, XM_001475631.1]",XM_001475631.1
1,chr17,RefSeq,CDS,6808204,6808245,.,+,0,"[Name=CDS:NC_000083.5:LOC100040603, Parent=XM_...","[Parent, XM_001475631.1,]",XM_001475631.1
2,chr17,RefSeq,CDS,6811792,6811869,.,+,2,"[Name=CDS:NC_000083.5:LOC100040603, Parent=XM_...","[Parent, XM_001475631.1,]",XM_001475631.1
3,chr17,RefSeq,exon,6806513,6806553,.,+,.,[Parent=XM_001475631.1],"[Parent, XM_001475631.1]",XM_001475631.1
4,chr17,RefSeq,five_prime_UTR,6806513,6806526,.,+,.,[Parent=XM_001475631.1],"[Parent, XM_001475631.1]",XM_001475631.1
...,...,...,...,...,...,...,...,...,...,...,...
507,chr17,RefSeq,exon,6812219,6818159,.,+,.,[Parent=XM_001475631.1],"[Parent, XM_001475631.1]",XM_001475631.1
508,chr17,RefSeq,protein,6806527,6812289,.,+,.,"[ID=, Parent=XM_001475631.1]","[Parent, XM_001475631.1]",XM_001475631.1
509,chr17,RefSeq,CDS,6806527,6806553,.,+,0,"[Name=CDS:NC_000083.5:LOC100040603, Parent=XM_...","[Parent, XM_001475631.1,]",XM_001475631.1
510,chr17,RefSeq,exon,6811792,6811869,.,+,.,[Parent=XM_001475631.1],"[Parent, XM_001475631.1]",XM_001475631.1
511,chr17,RefSeq,exon,6806513,6806553,.,+,.,[Parent=XM_001475631.1],"[Parent, XM_001475631.1]",XM_001475631.1

In [32]:
gff.groupby('XM', as_index=False) \
    .agg({'end': 'count'})

               XM  end
0  XM_001475631.1  479

In [33]:
gff.groupby('type', as_index=False) \
    .agg({'end': 'count'})

              type  end
0              CDS  170
1             exon  201
2   five_prime_UTR   47
3             mRNA   33
4          protein   29
5  three_prime_UTR   32